Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01c835443b86fe988
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: testingmachine
         
